### ISSUE TITLE
[1.18.2] Shields don't block Bleeding

### ISSUE THREAD

**Issue by java-jambalaya** [Majrusz/MajruszsProgressiveDifficultyMod#110]
Tested to work with just Majruszs' Progressive Difficulty (-1.18.2-1.4.4.jar, on Forge 40.1.69), attacks such as arrows from Skeletons and punches from Zombies can still inflict the Bleeding effect on players holding up a Shield.

**Comment by Majrusz** [comment]
Fixed 4800a49953f649c3dafe44440014ad663cad2056 gonna update mod soon

**Comment by INooBTooMuch** [comment]
> Fixed [4800a49](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/commit/4800a49953f649c3dafe44440014ad663cad2056) gonna update mod soon

It still happens in 1.18.2. Is there maybe a known mod conflict?

Version : 1.4.4
Forge : 40.1.92
Mods : [List](https://gist.github.com/INooBTooMuch/10cfa142657308873bc94d017f336ec9#file-mods-in-testing-v_1_8_11_1)
