### ISSUE TITLE
Bug on excluded mobs

### ISSUE THREAD

**Issue by sutepu-chan** [Majrusz/MajruszsProgressiveDifficultyMod#176]
Excluded mobs (Wither and Ender_dragon) are still buffed even if they are set to be the excluded mobs in config.
Here is what the config is
```toml
[Features.MobsSpawnStronger]
		#Specifies whether this is enabled.
		is_enabled = true
		#List of mobs that should not get health and damage bonuses. (for instance minecraft:wither)
		#Supports 'regular expressions' when text starts with {regex} prefix.
		excluded_mobs = ["{regex}cataclysm:.+", "minecraft:wither", "minecraft:ender_dragon"]
```

**Comment by Majrusz** [comment]
Hello, thanks for the report, there was a bug in my library mod that I fixed recently, check out the latest 5.1.1 version

**Comment by sutepu-chan** [comment]
There is a new bug after updating the mod. The pack automatically enters EXPERT MODE when entering the Nether no matter how I change the config
Here is the example for reference
```toml
#Game stage set at the beginning of a new world.
	#Allowed Values: NORMAL, EXPERT, MASTER
	default_mode = "NORMAL"

	#Determines what starts the Expert Mode.
	[GameStage.ExpertMode]
		#List of entities which start the game stage after killing them.
		#Supports 'regular expressions' when text starts with {regex} prefix.
		triggering_entities = ["minecraft:ender_dragon"]
		#List of dimensions which start the game stage after entering them.
		#Supports 'regular expressions' when text starts with {regex} prefix.
		triggering_dimensions = [""]

	#Determines what starts the Master Mode.
	[GameStage.MasterMode]
		#List of entities which start the game stage after killing them.
		#Supports 'regular expressions' when text starts with {regex} prefix.
		triggering_entities = ["cataclysm:ender_guardian"]
		#List of dimensions which start the game stage after entering them.
		#Supports 'regular expressions' when text starts with {regex} prefix.
		triggering_dimensions = [""]
```

**Comment by sutepu-chan** [comment]
Hi, I just find that the above (the exluded mobs) still does not work
I use the same config as before

**Comment by Majrusz** [comment]
Hello, thanks for the report, there was another bug in my library mod. Check out the latest 5.1.2 library version, it should work properly now and let me know if it fixed this issue
